CREATE DATABASE  IF NOT EXISTS `log` 
USE `log`;

DROP TABLE IF EXISTS `log`;

CREATE TABLE `log` (
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOG_CREATION` datetime NOT NULL,
  `LOG_TYPE` enum('LOGIN_USER','SIGNUP_USER','DELETE_USER','UPDATE_USER','LOGOUT_USER') DEFAULT NULL,
  `LOG_MESSAGE` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(100) NOT NULL,
  `USER_PASSWORD` varchar(150) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`),
  UNIQUE KEY `USER_NAME_2` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

